version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
    - /v?\d+\.\d+\.\d+/
configuration: Release
platform: x86
before_build:
  - git submodule update --init --recursive
  - git clone https://github.com/andburn/powershell.git C:\projects\build\Powershell
  - ps: .\Scripts\bootstrap.ps1
  - ps: .\Scripts\appveyor.ps1 EndGame -PreBuild
build:
  project: EndGame.sln
  verbosity: minimal
after_build:
- ps: .\Scripts\appveyor.ps1 EndGame -PostBuild
after_test:
- ps: .\Scripts\appveyor.ps1 EndGame -PostTest
deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: Update $(APPVEYOR_REPO_TAG_NAME)
  description: Description
  auth_token:
    secure: FwL5p581MbZH+QA+4YW2G9SfjypFLWXRFbmNwZmo51i+hm3ugRyEvJMyZO7s7uDs
  artifact: Release
  draft: true
  on:
    APPVEYOR_REPO_TAG: true
